# Descomposición de matrices
Consiste en reescribir una matriz cuadrada X como un producto de A x B x C, es decir X = AxBxC, donde:
- A: es la matriz formada por los autovectores
- B: matriz diagonal formada por los autovalores
- C: matriz inversa de A.

Por ejemplo: Cuando tenemos el 6, se puede escribir 3*2=6 y el 3 y 2 tienen la propiedad de ser numeros primos.

## Metodo 1 escribir matriz
### Escribir matriz a la inversa
Usar este metodo puede ser computacionalmente dificil cuando

In [7]:
import numpy as np

A = np.array([[3,2], [4,1]])
print(A)

[[3 2]
 [4 1]]


In [8]:
autovalores, autovectores = np.linalg.eig(A)
print(autovalores)
print(22*'-')
print(autovectores)

[ 5. -1.]
----------------------
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [12]:
A_calculada = autovectores.dot(np.diag(autovalores)).dot(np.linalg.inv(autovectores))
A_calculada

array([[3., 2.],
       [4., 1.]])

## Metodo 2 escribir matriz
### Si es una matriz real y simetrica se utilizara la traspuesta
Usar este metodo trae muchos beneficios cuando en las matrices reales y simétricas, C = A.T (matriz traspuesta de los autovectores). Esta propiedad tiene menor costo computacional.

In [17]:
A = np.array([[3,2], [2,3]])
print(A)

[[3 2]
 [2 3]]


Demostramos que esta matriz es simétrica, ya que coincide con su traspuesta

In [19]:
print(A == A.T)

[[ True  True]
 [ True  True]]


In [24]:
# Calculamos de nuevo los autovalores y los autovectores
autovalores, autovectores = np.linalg.eig(A)
print(autovalores)
print(autovectores)

[5. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


Resultado

In [22]:
A_calculada = autovectores.dot(np.diag(autovalores)).dot(autovectores.T)
A_calculada

array([[3., 2.],
       [2., 3.]])

## Convulsión: 
Podemos escribir a nuestra matriz cuando es cuadrada en función de los autovalores y autovectores, y en el caso de que sea simétrica podemos usar la traspuesta en lugar de la inversa.