# ¿Qué es una pseudo inversa de Moore Penrose y cómo calcularla?

- La pseudo inversa de Moore Penrose es utilizada cuando en un sistema de ecuaciones lineales representado por Ax = B, x no tiene inversa.
- La pseudo inversa de MP es única y existe si se verifican 4 condiciones.
- Para calcularla se siguen los siguientes pasos:
- Calcular las matrices U, D, y V (matrices SVD) de A.
    1. Construir D_pse: una matriz de ceros que tiene igual dimension de A, y que luego se transpone.
    2. Reemplazar la submatriz D_pse[: D.shape[0], : D.shape[0]] por np.linalg.inv(np.diag(D))
    3. Reconstruir pseudoinversa: A_pse = V.T.dot(D_pse).dot(U.T)
**Notas**
- Caclular con numpy ``np.linalg.pinv(A)``. Numpy usa SVD es mas certera, y computacionalmente más efectiva.
- Lo que obtenemos con A_pse es una matriz muy cercana a la inversa. Cercano en el sentido de que minimiza - la norma dos de estas distancias. O sea, de estos errores que estamos cometiendo.
- A_pse no es conmutativa, es decir, A_pse·A ≠ A·A_pse

In [1]:
import numpy as np
# No mostrar los numeros que son muy cercanos a cero
np.set_printoptions(suppress=True)

A = np.array([[2, 3], [5, 7], [11, 13]])
print(A)

[[ 2  3]
 [ 5  7]
 [11 13]]


In [2]:
U, D, V = np.linalg.svd(A)
print(f"U: {U}\n")
print(f"D: {D}\n")
print(f"V: {V}\n")



U: [[-0.18499741 -0.47276624 -0.86154979]
 [-0.44249308 -0.74271297  0.50257071]
 [-0.87748267  0.4742041  -0.07179582]]

D: [19.40321383  0.71783924]

V: [[-0.63055377 -0.77614557]
 [ 0.77614557 -0.63055377]]



Generando una matriz llena de 0

In [3]:
D_pse = np.zeros((A.shape[0], A.shape[1])).T
D_pse

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
print("Valores a reemplazar en D_pse")
print(D_pse[:D.shape[0], :D.shape[0]])

Valores a reemplazar en D_pse
[[0. 0.]
 [0. 0.]]


In [5]:
print("Valores que pondremos en D_pse")
print(np.linalg.inv(np.diag(D)))

Valores que pondremos en D_pse
[[0.05153785 0.        ]
 [0.         1.39306957]]


In [6]:
print("D_pse")
D_pse[:D.shape[0], :D.shape[0]] = np.linalg.inv(np.diag(D))
print(D_pse)

D_pse
[[0.05153785 0.         0.        ]
 [0.         1.39306957 0.        ]]


## Metodo 1 Calculando la pseudo inversa de A

In [7]:
A_pse = V.T.dot(D_pse).dot(U.T)
print(A_pse)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


## Metodo 2 Calculando la pseudo inversa de A con Numpy

In [8]:
A_pse_calc = np.linalg.pinv(A)
print(A_pse_calc)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


## Metodo 3 Calculando la pseudo inversa de A

In [9]:
A_pse_2 = np.linalg.inv(A.T.dot(A)).dot(A.T)
print(A_pse_2)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


Comprobando la pseudo inversa

In [10]:
print(A_pse)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]
